// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE6ajwfpE-R3TzUKyPeBGG9YA8axEUMwE',
    appId: '1:408189535372:web:c12dd3a8442329ea3527a9',
    messagingSenderId: '408189535372',
    projectId: 'globalcard-ff50f',
    authDomain: 'globalcard-ff50f.firebaseapp.com',
    storageBucket: 'globalcard-ff50f.firebasestorage.app',
    measurementId: 'G-28510TN4DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP-9dDNFQ2CaKOiuXfc5SRaf-QM1GhNoA',
    appId: '1:408189535372:android:cd0e308021b45a403527a9',
    messagingSenderId: '408189535372',
    projectId: 'globalcard-ff50f',
    storageBucket: 'globalcard-ff50f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPU339ns_29W5Uj2Ive-uCwcrc-rAgRQc',
    appId: '1:408189535372:ios:003c170505da32a93527a9',
    messagingSenderId: '408189535372',
    projectId: 'globalcard-ff50f',
    storageBucket: 'globalcard-ff50f.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPU339ns_29W5Uj2Ive-uCwcrc-rAgRQc',
    appId: '1:408189535372:ios:003c170505da32a93527a9',
    messagingSenderId: '408189535372',
    projectId: 'globalcard-ff50f',
    storageBucket: 'globalcard-ff50f.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE6ajwfpE-R3TzUKyPeBGG9YA8axEUMwE',
    appId: '1:408189535372:web:db6695a2752190523527a9',
    messagingSenderId: '408189535372',
    projectId: 'globalcard-ff50f',
    authDomain: 'globalcard-ff50f.firebaseapp.com',
    storageBucket: 'globalcard-ff50f.firebasestorage.app',
    measurementId: 'G-X7K9P7YTNY',
  );
}
